# syntax=docker/dockerfile:1

## Labels to apply to image
#LABEL author="Dr H"
#LABEL service="query_service"
#LABEL version="1.0"

# Alpine is chosen for its small footprint
# compared to Ubuntu
FROM golang:1.17-alpine

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

# Download necessary Go modules
RUN go mod download

COPY *.go ./

RUN go build -o /service

EXPOSE 8080

CMD [ "/service" ]